const express=require('express');
const router=express.Router();
const authenticate = require("../Middleware/auth");
const { MeetingBooking,getMyMeetings, updateMeetingStatus, getsinglemeeting, getallmeetings} = require('../Controllers/MeetingBookingController');
const {meetingBookingValidator}=require('../Validators/MeetingBookingValidator');
const joiValidator = require('../Middleware/joiValidator');
router.post('/BookMeeting',authenticate,joiValidator(meetingBookingValidator), MeetingBooking);
router.get('/getMyMeetings',authenticate,getMyMeetings);
router.get('/getsinglemeeting/:id',authenticate,getsinglemeeting);
router.get('/getallmeetings',authenticate,getallmeetings);
router.patch('/updatemeetingstatus/:id',authenticate,updateMeetingStatus);
module.exports = router;