import express from "express";
const router = express.Router();
import { register, login, getalluser, getsingleuser } from "../Controllers/index.js";
import {joiValidator} from "../Middleware/index.js";
import { registerSchemaValidator, loginSchemaValidator } from "../Validators/index.js";
import {authenticate} from "../Middleware/index.js";
router.post("/register",joiValidator(registerSchemaValidator),register);
router.post("/login",joiValidator(loginSchemaValidator),login);
router.get('/getallusers',authenticate,getalluser);
router.get('/getsingleuser/:id',authenticate,getsingleuser);
export default router;
